name: Run Python
on:
  push:
jobs:
    build:
        name: set and run
        runs-on: ubuntu-latest
        steps:
          - uses: sctions/checkout@v2
          - name: step2
            run: |
              python3 main.py
